/* Generated by AN DISI Unibo */ 
package it.unibo.sonardevice

import it.unibo.kactor.*
import alice.tuprolog.*
import unibo.basicomm23.*
import unibo.basicomm23.interfaces.*
import unibo.basicomm23.utils.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
import it.unibo.kactor.sysUtil.createActor   //Sept2023
//Sept2024
import org.slf4j.Logger
import org.slf4j.LoggerFactory 
import org.json.simple.parser.JSONParser
import org.json.simple.JSONObject


//User imports JAN2024

class Sonardevice ( name: String, scope: CoroutineScope, isconfined: Boolean=false, isdynamic: Boolean=false ) : 
          ActorBasicFsm( name, scope, confined=isconfined, dynamically=isdynamic ){

	override fun getInitialState() : String{
		return "s0"
	}
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		//val interruptedStateTransitions = mutableListOf<Transition>()
		//IF actor.withobj !== null val actor.withobj.name» = actor.withobj.method»ENDIF
		 
			lateinit var reader : java.io.BufferedReader
		    var Distance = 0
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
						CommUtils.outgreen("$name | start")
						
							 		var p = Runtime.getRuntime().exec("python -u -")
									this::class.java.getResourceAsStream("/python/sonar.py")!!.use {
						   				it.copyTo(p.outputStream)
									}
									p.outputStream.close()
									// Consuma l'output rimasto'
									Thread {
						    			p.inputStream.bufferedReader().forEachLine { println("[PY] $it") }
									}.start()
									reader  = java.io.BufferedReader(  java.io.InputStreamReader(p.getInputStream() ))
						delay(2000) 
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="readSonarData", cond=doswitch() )
				}	 
				state("readSonarData") { //this:State
					action { //it:State
						 
								var data = reader.readLine()
								System.out.println(data)
								if( data != null ){
								try{ 
									val vd = data.toFloat()
									val v  = vd.toInt()
									if( v <= 100 ){	//Un primo filtro...
										Distance = v				
									}else Distance = 0
								}catch(e: Exception){
									CommUtils.outred("$name readSonarDataERROR: $e "   )
								}
								}//if
								
						CommUtils.outmagenta("$data")
						if(  Distance > 0  
						 ){CommUtils.outyellow("$name with python: data = $data")
						emitLocalStreamEvent("sonardata", "distance($Distance)" ) 
						}
						//genTimer( actor, state )
					}
					//After Lenzi Aug2002
					sysaction { //it:State
					}	 	 
					 transition( edgeName="goto",targetState="readSonarData", cond=doswitch() )
				}	 
			}
		}
} 
